### PR TITLE
KAT-392 including server agent on openfire chef

### PR DESCRIPTION
**Pull request by ryanhallcs**
@mattminer-rally @toofishes @arnaud036

### CODE REVIEW

**Comment by mattminer-rally** [comment]
LGTM

**Comment by toofishes** [comment]
LGTM

**Comment by arnaud036** [comment]
Wrong cookbook! Should be done in the wrapper cookbook https://github.com/AudaxHealthInc/rally-optumapi-cookbook

**Comment by scalp42** [comment]
agree with @arnaud036 wrong cookbook.

**Comment by scalp42** [comment]
(vivi :fr: :fries:)

**Comment by scalp42** [comment]
PS: we miss you @cgphillips

**Comment by scalp42** [comment]
also @ryanhallcs you forgot to update the metadata and point to the cookbook in the Berksfile :sake: 

cc @bookest

**Comment by petercoons** [comment]
wut

**Comment by rwhiten1** [comment]
@scalp42  Vas te faire voir chez les grecs! :trollface:

**Comment by bookest** [comment]
LGMT

**Comment by rwhiten1** [comment]
Damn, its an ex-rally party up in hurrrr!!! hey @bookest !  WhereTF are CK and Sabo at? :trollface:

**Comment by scalp42** [comment]
it's missing @otakup0pe :maple_leaf:

**Comment by scalp42** [comment]
hi @kfjeldheim !

**Comment by scalp42** [comment]
@tomf861

**Comment by scalp42** [comment]
Peace!   

cc @joeyparsons

**Comment by otakup0pe** [comment]
LGTM :100:

**Comment by joeyparsons** [comment]
:scream_cat: :water_buffalo: :moneybag: :santa: @scalp42

**Comment by code-crimes** [comment]
Post-audaxers party?

vincent

**Comment by ryanhallcs** [comment]
sorry folks party over, moved to https://github.com/AudaxHealthInc/chef/pull/3289

**Comment by otakup0pe** [comment]
@code-crimes more like

**Comment by otakup0pe** [comment]
j/k i hope everyone is doing well and has enjoys a lovely holiday break :tophat:

**Pull request closed without merging**
